### ISSUE TITLE
Ability to copy credentials

### ISSUE THREAD

**Issue by Necklaces** [nthdimtech/signet-client#10]
Instead of making the Signet type the credential as a keyboard, I would like to be able to copy the credentials into my clipboard (after pushing the physical button to confirm the copy, of course). Is this possible?

**Comment by nthdimtech** [comment]
It's possible I'm just not sure the best way to implement it. It could be done as a right click option or there could be a setting which would change the action that the  primary icon buttons perform.  For now if you go to the open/edit dialog for an account you will see keyboard buttons next to each field which will copy the field to clipboard.

On December 28, 2017 11:08:41 AM PST, Necklaces <notifications@github.com> wrote:
>Instead of making the Signet type the credential as a keyboard, I would
>like to be able to copy the credentials into my clipboard (after
>pushing the physical button to confirm the copy, of course). Is this
>possible?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-desktop-client/issues/10

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Necklaces** [comment]
I was thinking about adding some "Copy password" and "Copy username" buttons in the right click menu (AccountActionBar::defaultAction). I can't use the edit menu as that shows my password by default (maybe change that to a password field? For example EchoMode set to Password on a QLineEdit field).
