### ISSUE TITLE
Entries not sorted alphabetically - 0.9.13.4

### ISSUE THREAD

**Issue by TARDIS2** [nthdimtech/signet-client#128]
The client does not sort the account entries alphabetically, but in the order they were stored (version 0.9.13.4, device firmware version 1.3.1, Windows 7 64 bit). Shouldn't this happen by default?

Thanks in advance!

**Comment by nthdimtech** [comment]
I have considered this from time to time. The combination of the search feature and the groups makes visually searching by letter not as important so I've never got around to it. I'll see about doing this for the next release.

**Comment by nthdimtech** [comment]
Fixed by commit 4a63120
