### ISSUE TITLE
Link broken "Check for new version"

### ISSUE THREAD

**Issue by timetoseek** [nthdimtech/signet-client#130]
Please note broken link to check for new firmware versions from the Windows client:
![check_new_firmware_version](https://user-images.githubusercontent.com/26972658/60740372-478e8780-9f1a-11e9-9c1e-6c4dab9f8fd0.jpg)
![firmware_update_link_error](https://user-images.githubusercontent.com/26972658/60740375-48bfb480-9f1a-11e9-8648-3cd17d41039b.jpg)

**Comment by nthdimtech** [comment]
Thanks for letting me know. I think this used to be a symlink. I had to rebuild the server recently and I must have not added the link back.

On July 5, 2019 11:48:13 AM PDT, timetoseek <notifications@github.com> wrote:
>Please note broken link to check for new firmware versions from the
>Windows client:
>![check_new_firmware_version](https://user-images.githubusercontent.com/26972658/60740372-478e8780-9f1a-11e9-9c1e-6c4dab9f8fd0.jpg)
>![firmware_update_link_error](https://user-images.githubusercontent.com/26972658/60740375-48bfb480-9f1a-11e9-8648-3cd17d41039b.jpg)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-client/issues/130

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nthdimtech** [comment]
Added the symlink back on the server and change the URL in the code to the direct link. FYI there is no new release yet but there should be a in a day or two.
