### ISSUE TITLE
Release Notes for v. 0.9.14

### ISSUE THREAD

**Issue by Airgunster** [nthdimtech/signet-client#134]
Hi Niels,

Could you please provide Release Notes for v. 0.9.14?
(https://nthdimtech.com/signet/release-notes/20190709_signet-client-0.9.14-notes which is referenced on https://nthdimtech.com/signet/downloads/ page does return HTTP/1.1 404)

Thanks in advance,
Alexey

**Comment by nthdimtech** [comment]
Thanks for reminding me. Release notes added to the source code and the website.
