### ISSUE TITLE
Signet browser extension: Shortcuts

### ISSUE THREAD

**Issue by Airgunster** [nthdimtech/signet-client#136]
Hi there,

It would be nice to introduce shortcuts for Signet browser (Firefox, Chrome) extension so you don't need to click and use keyboard instead.

_Pollisbly it already exist, but I wasn't able to find any documentation about it, so appreciate if anyone can share details, if any._

Thanks a lot in advance,
Alexey

**Comment by nthdimtech** [comment]
There is a shortcut to login with autofill CTRL+SHIFT+L which works if 
the indicator dot is green. If the indicator dot is yellow it just 
launches the menu. Are you thinking of a keyboard typing specific shortcut?

**Comment by Airgunster** [comment]
@nthdimtech, Indeed, we have `CTRL`+`SHIFT`+`L` shortcut which I was not aware of! It would be nice to consider (in future releases) ability to set your own keys to trigger Signet extension, just in case if `CTRL`+`SHIFT`+`L` is already busy with something else. Thanks again for the Signet Neils!

**Comment by dragon788** [comment]
In Chrome if you open the Extensions page, on left hand side I believe there's an option for Keyboard Shortcuts and then you can go to the Signet extension in that list and change the shortcut. Not sure if there is something similar for Firefox.

**Comment by Airgunster** [comment]
@dragon788, thanks! Indeed in Firefox we have [extension shortcuts](https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox), never seen that before.
