### ISSUE TITLE
segmentation fault after loading content from USB (Debian buster)

### ISSUE THREAD

**Issue by ngiger** [nthdimtech/signet-client#138]
On my Debian stretch system (AMD64) I get a segmentation fault
[signet_problem.txt](https://github.com/nthdimtech/signet-client/files/3642239/signet_problem.txt)

I compiled signet-client from source code.

After launching it and inserting the USB signet key it prompts for my password. After entering it starts decrypting the content which takes a few seconds. When it reaches the end it crashes with a segmentation fault. Stacktrace is attached.

**Comment by nthdimtech** [comment]
Sorry for the delay in responding to this. I've studied the stack trace and I believe that one of your database entries is malformed and it's crashing when the entry is parsed. I'm going to add some extra checks in the parser then hopefully we can figure out how the entry got in a bad state to begin with.

**Comment by nthdimtech** [comment]
Just pushed a quick commit targeting this specific crash. I'll make a broader validation effort once I have a sense of what the original cause was.

**Comment by ngiger** [comment]
Sorry for not reporting back earlier. Your commit fixed my problem and I am now able to open my database without any problem.

It is okay for me if you close this bug.

Thanks a lot for your work!
