### ISSUE TITLE
`Backup to file` doesn't work anymore on macOS (10.15.0) Catalina

### ISSUE THREAD

**Issue by Airgunster** [nthdimtech/signet-client#144]
Hi there,

I'm currently using macOS (10.15.0) Catalina with my Signet, and `Backup to file` feature stopped working, macOS (10.14.6) Mojave had no issues with `Backup to file` feature.

Reproduction steps,
1. Start `signet` app;
2. `signet` app will detect that there was no backups created for last 7 days and will ask to create one; Answer `Yes`;
3. `Backup to file` dialogue will be closed and nothing will happen; Light will not blink on Signet device, `signet` app remains showing list of entries;
4. Shutdown `signet` client; Disconnect Signet device from USB port;
5. Insert Signet device into USB port; Start `signet` app; Repeat steps 1-3, observe no change in behavior;

```
Signet client: 0.9.14
Firmware version: 1.3.4
```

**Comment by nthdimtech** [comment]
Strange. What if you say "no" to the prompt and then try to do it from the device menu? I fixed an issue with regard to automatic backups awhile back so maybe that is it.

I really need to do a new release soon and I'll upgrade my macOS while I'm at it so hopefully I'll nail this issue for sure then.

**Comment by Airgunster** [comment]
@nthdimtech, I've tried that already actually (sorry for not being verbose on that). If I select _No_, and do it via _Device > Backup to file_ then exact same behavior is happening as I've explained in _Reproduction steps_.

**Comment by nthdimtech** [comment]
Until I get to making a new release (probably next week), the only thing I can think to suggest is to try an older client and see if the backup works. The backup feature has not changed since even the early versions of client.

**Comment by Airgunster** [comment]
@nthdimtech, Thanks for the hint. I was able to backup with Signet v. 0.9.10 via _no backups created for last 7 days_ dialogue, however was not able to backup via _Device > Backup to file_ menu (I've tried many old versions (Signet v. 0.9.7 0 0.9.13)).

**Comment by Airgunster** [comment]
@nthdimtech , Hi Neils, by any chance, do you have any rough ETA for the next release of Signet v. 0.9.15 with a fix for macOS Catalina (10.15.X)? Thanks in advance!

**Comment by Airgunster** [comment]
Any news for v. 0.9.15? If any tests on macOS Catalina are required, feel free to ping me (will be glad to help testing it).

**Comment by nthdimtech** [comment]
Sorry for the delays. It's hard to multitask Signet and Signet HC work. I'll be reaching a key milestone on HC in a week and can play catch up on Signet then.

On January 18, 2020 9:09:25 AM PST, Airgunster <notifications@github.com> wrote:
>Any news for v. 0.9.15? If any tests on macOS Catalina are required,
>feel free to ping me (will be glad to help testing it).
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-client/issues/144#issuecomment-575919059

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nthdimtech** [comment]
The Signet HC client work is finally merged with the main branch so it will be easy for me to take on Signet issues now. The next release should come in a matter of days, biggest thing holding me back now is a working MacOS build.

@Airgunster, I've upgraded to Catalina and I'm having bigger problems, current and previous clients don't even detect the device for me. Can you confirm that your client is working fine with your device?

**Comment by Airgunster** [comment]
@nthdimtech, Hi Neils, yep, can confirm that my Signet works fine (except the issue I've mentioned here) on macOS 10.15, I'm now on the latest release of macOS 10.15.3 (19D76) and Signet client v. 0.9.14 (firmware 1.3.4), here is the info about mine,

```
$ system_profiler SPUSBDataType
USB:
    USB 3.1 Bus:
      Host Controller Driver: AppleIntelCNLUSBXHCI
      PCI Device ID: 0x9ded
      PCI Revision ID: 0x0030
      PCI Vendor ID: 0x8086

        USB2.0 Hub:
          Product ID: 0x100f
          Vendor ID: 0x05ac (Apple Inc.)
          Version: 45.28
          Speed: Up to 480 Mb/s
          Manufacturer: Apple Inc.
          Location ID: 0x14300000 / 1
          Current Available (mA): 500
          Current Required (mA): 100
          Extra Operating Current (mA): 0

            4-Port USB 2.0 Hub:
              Product ID: 0x5411
              Vendor ID: 0x0bda  (Realtek Semiconductor Corp.)
              Version: 1.21
              Speed: Up to 480 Mb/s
              Manufacturer: Generic
              Location ID: 0x14310000 / 2
              Current Available (mA): 500
              Current Required (mA): 0
              Extra Operating Current (mA): 0

                Signet:
                  Product ID: 0x0001
                  Vendor ID: 0x5e2a
                  Version: 4.83
                  Speed: Up to 12 Mb/s
                  Manufacturer: Nth Dimension
                  Location ID: 0x14313000 / 5
                  Current Available (mA): 500
                  Current Required (mA): 100
                  Extra Operating Current (mA): 0
```

**Comment by nthdimtech** [comment]
Okay it was working for me all along. Stupid mistake, I have a KVM switch between my Mac Mini and Windows and forgot to move the device over to the USB hub connected to the switch.

I've updated my Mac to the latest as well. Everything is working except the application is triggering a security exception when I download the DMG despite the application being signed and my developer subscription being up to date. @Airgunster, could you check if you see the same problem? I've done a soft release of 0.9.15: https://www.nthdimtech.com/signet/downloads/. The main download links work (for all OS's) but I haven't got to signing everything, making the source archive, release notes, etc. My Mac says that it can't run the application because it "can't determine if it contains malware" (I forget the exact quote). Let me know what you get.

**Comment by Airgunster** [comment]
@nthdimtech, Downloaded v. 0.9.15 and got _This software needs to be updated. Contact the developer for more information_,

![Screenshot 2020-02-10 at 10 47 09](https://user-images.githubusercontent.com/7937957/74143726-3fef3980-4bf3-11ea-959d-87231b96cecd.png)

However if I click on _Show in Finder_ and then open it with CTRL+LEFT-CLICK and select open I'm able to start it up.

**Comment by nthdimtech** [comment]
Yeah I've got that error before also. Both "codesign" and "spctl" say the app is fine but the error goes away when gatekeeper (the application the makes the final decision) is disabled. With so little information to go on I might have to try to get support from Apple to fix it.

On February 10, 2020 2:51:27 AM PST, Airgunster <notifications@github.com> wrote:
>@nthdimtech, Downloaded v. 0.9.15 and got _This software needs to be
>updated. Contact the developer for more information_,
>
>![Screenshot 2020-02-10 at 10 47
>09](https://user-images.githubusercontent.com/7937957/74143726-3fef3980-4bf3-11ea-959d-87231b96cecd.png)
>
>However if I click on _Show in Finder_ and then open it with
>CTRL+LEFT-CLICK and select open I'm able to start it up.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-client/issues/144#issuecomment-584064614

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nthdimtech** [comment]
I did some more research and found that the issue is that the software for Catalina now needs to be signed and go through a notarization process where the software is uploaded to Apple and checked for certain properties (not clear on what). For the short term I think I'll just add advice to the downloads page about working around it and come back to notarization later.

**Comment by nthdimtech** [comment]
@Airgunster, back on topic. Do you still have issues creating backups?

**Comment by Airgunster** [comment]
@nthdimtech, Thanks,

> Do you still have issues creating backups?

Actually yes, upgraded to v. 0.9.15 and still same issue (Backup to file modal will be closed and nothing will happen; Light will not blink on Signet device, signet app remains showing list of entries).

**Comment by Airgunster** [comment]
@nthdimtech, Hi Neils, do you have any further update on this?

**Comment by Airgunster** [comment]
@nthdimtech, Ping, any news?

**Comment by nthdimtech** [comment]
Sorry for the long delay. I believe it is fixed. It seemed to be a policy change in Mac OS that limited the ways that file dialog's can be created.

I also noticed that the settings dialog also had a new crash and fixed that while I was on my Mac. 

You can build it now if you have the time or wait a few days for a new release. This upcoming release will be the one that will ship with Signet HC which should be shipping by the end of the month BTW (finally). One big thing I changed is adjusted the pixel sizes of the fonts and icons based on screen resolution and chose a uniform style on all platforms to hopefully lower my maintenance overhead. If you do build it let me know what you think. Things will look bigger than they used to. The idea is reduce the time you need to hunt for the item or action with the mouse.

**Comment by nthdimtech** [comment]
I've uploaded the latest release: https://nthdimtech.com/downloads/signet-releases/0.9.16/

Let me know if it solves the problem for you and I'll close this out.

**Comment by Airgunster** [comment]
@nthdimtech, Hi Neils, just saw your replies (apologies for the delay).

Tested new v. 0.9.16 on macOS 10.15.4 and Backup to file modal works perfectly now (also new look and feel is extremely nice (thanks for that!)).
