### ISSUE TITLE
Database migration from Signet to Signet HC

### ISSUE THREAD

**Issue by Airgunster** [nthdimtech/signet-client#148]
Hi Neils,

I've got my Signet HC (thanks!) and discovered that all my database backups are in `signet-hc-YYYY-MM-DD.sdb` format while _Restore from backup_ option allows to select only `signet-hc-YYYY-MM-DD.sdbhc` database backups.

Can you please clarify how to migrate Signet database to Signet HC? (I remember that it should be backward compatible)

Thanks in advance,
Alexey

**Comment by nthdimtech** [comment]
I'm working on that right now and I am planning on a campaign update about it since it's so important.

The way I settled on supporting migration is CSV export on Signet followed by CSV import on Signet HC. I changed the CSV export function so that it exports to a zip file with one file per data type to make things complete and clear. I wanted to have this done before people got their Signet HC's but they shipped faster than I could code it. I'll probably have this in a new release by tomorrow and push a campaign update shortly after that.

**Comment by nthdimtech** [comment]
Very close to completing this. It's working well on Windows and GNU/Linux but there is a MacOS specific issue that requires some rework.

**Comment by nthdimtech** [comment]
Fixed and released: 

https://www.nthdimtech.com/signet/downloads
http://nthdimtech.com/downloads/signet-releases/0.9.17/

To migrate your data:

1) Insert your Signet and unlock it
2) Click the "export->CSV" menu item. It should create a ZIP file with one file for each data type
3) Remove your Signet and insert your Signet HC (the client is not yet able to dynamically switch between devices)
4) Unlock your Signet HC and click the "Import->CSV" menu item and select the previously created ZIP file
5) You will be asked where the data from each file should go. For migration you should click "Ok" to confirm the default selection. This is more useful if the CSV's came from a different source and you want to fixup some of the type names.
6) Press and hold the device button and all of your old data should appear

I'm going to put all this info in a guide and in the upcoming campaign release as well. Once I get confirmation that this is working for other people I'll close out this bug.

**Comment by nthdimtech** [comment]
I've got multiple reports of CSV based migration working in the new release so I'm closing this.

**Comment by Airgunster** [comment]
@nthdimtech, Thanks! I've migrated all records successfully. I've seen that field types were all converted into _Text_ type (i.e. they were not preserved), just my observation.

**Comment by nthdimtech** [comment]
Yes I think there are still problems with data type definition importing. I'll investigate and file a bug on it. At least that it's not hard to modify the data type definitions after import.

On May 22, 2020 10:37:36 AM PDT, Airgunster <notifications@github.com> wrote:
>@nthdimtech, Thanks! I've migrated all records successfully. I've seen
>that field types were all converted into _Text_ type (i.e. they were
>not preserved), just my observation.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-client/issues/148#issuecomment-632822926

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nthdimtech** [comment]
@Airgunster 

Regarding data type importing see bug #153. I should get this by the next release.
