### ISSUE TITLE
git submodule update --init fails "not our ref 33d8469755d6199ceefc30871d8261034f39fc84"

### ISSUE THREAD

**Issue by ngiger** [nthdimtech/signet-client#151]
After a git pull of the master branch, I am on 0537aeb51d4022095b1b6925d8ea27e93a93f921.
calling
> git submodule update --init

fails with

> fatal: remote error: upload-pack: not our ref 33d8469755d6199ceefc30871d8261034f39fc84
Fetched in submodule path 'signet-base', but it did not contain 33d8469755d6199ceefc30871d8261034f39fc84. Direct fetching of that commit failed.

**Comment by nthdimtech** [comment]
Forgot to push a signet-base change. Fixed.
