### ISSUE TITLE
Export to CSV should escape ,

### ISSUE THREAD

**Issue by dr4Ke** [nthdimtech/signet-client#19]
Currently, the export to CSV of values containing a `,` is not OK. The character cannot be distinguished from the separator:

    typeName,name,username,password,url,email,
    Accounts,Test using a , char,dr4Ke,n5W,auenstaunsrtsdp,,,,

Perhaps we should use quotes for such values. Ex:

    typeName,name,username,password,url,email,
    Accounts,"Test using a , char",dr4Ke,"n5W,auenstaunsrtsdp",,,,

Then, if the `"` character is used together with `,`, we should escape it with another one `""`, says the [RFC](https://tools.ietf.org/html/rfc4180).

**Comment by nthdimtech** [comment]
Good catch. I'm a little concerned about that escapement method since I've never seen it before. I'm going to want to do a survey of what different programs will accept and give some options if "" is not universal

**Comment by nthdimtech** [comment]
I've fixed this in commit ad7c0cd. I just quoted everything for simplicity and escaped " with "" as per the RFC. It's parsed correctly by libreoffice and that's a good enough for now. I will look at some other programs later and open a bug if they don't parse the output right.

**Comment by dr4Ke** [comment]
Nice. FYI, Microsoft Excel (Office 365 Pro) supports this too.
