### ISSUE TITLE
Crowdsupply's website for Signet down

### ISSUE THREAD

**Issue by lwiechec** [nthdimtech/signet-client#28]
Tried to check the 0.9.7 build release from [Signet Crowdsupply webpage](https://www.crowdsupply.com/nth-dimension/signet) and all I am getting is 'website down' page: 
![signet_website_down](https://user-images.githubusercontent.com/376537/34990812-b4e4f06a-fac7-11e7-9742-f584eb62f1e4.png)

**Comment by Airgunster** [comment]
Looks like it was a temporary issue with crowdsupply.com, now everything works OK.

**Comment by nthdimtech** [comment]
Not sure what happened, I only supply the content. I'm glad it's up again though
