### ISSUE TITLE
Crash on macOS after timeout to press button

### ISSUE THREAD

**Issue by Airgunster** [nthdimtech/signet-client#29]
Hey there,

I've just started to use Signet and detected my first issue on macOS. Signet will always crash right after timeout to press button (after executing 'Login').

How to reproduce,
1. Run Signet app;
2. Type in search any text to match your entry;
3. Press `ENTER` and select `Login`;
4. Wait 10 seconds without doing anything (i.e. do not select any field to auto-type your login/password), until timeout will happen;
5. Observe crashed Signet app;

It's pretty easy to reproduce the issue, however if any logs/traces necessary from my side, I would be happy to assist.

Could you please have a look?

Thanks a lot in advance,
Alexey

**Comment by nthdimtech** [comment]
I was able to reproduce it with your instructions, thanks.

The application was reading uninitialized response data in error cases (in this case timeout). In theory it could affect any platform. Commit 6bc82a98 should fix it. You shouldn't see this in the 0.9.8 release when it comes out.

**Comment by Airgunster** [comment]
Cool, thanks for a quick fix.
