### ISSUE TITLE
Add guide on howto build in the readme

### ISSUE THREAD

**Issue by ngiger** [nthdimtech/signet-client#44]
A long time ago I worked with C++.

Also it would be nice a have somewhere a list of requisite.

If you help me compile, I could generate a .travis.yml to help you build and test after each checkin using https://travis-ci.org/

**Comment by nthdimtech** [comment]
Building is pretty simple.  You just run qmake on "client/client.pro" then run make.

For prerequisites you need development packages for Qt, zlib, libX11, and GnuPG. The main thing holding me back from providing exact build instructions is the package names for these dependencies on various GNU/Linux systems. I also want to describe how to do builds for MacOS and Windows which have their own unique setup steps.

**Comment by nthdimtech** [comment]
I've just added build instruction for all platforms in "BUILDING.md". I'm going to assign the bug to you. If you are able to build from the instructions feel free to close it, otherwise let me know and I'll clarify the instructions.

**Comment by nthdimtech** [comment]
I've tested the steps recently on all three platforms so I think it's okay to close this. Any more specific problems with building can be handed in a different issue

**Comment by ngiger** [comment]
Thanks a lot
