### ISSUE TITLE
Missing XGetKeyboardMapping when building on Debian Stretch

### ISSUE THREAD

**Issue by ngiger** [nthdimtech/signet-client#46]
I followed the instructions in building.md for my Debian Stretch, but got the following error:

> g++ -m64 -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o signet signetdev.o entryrenamedialog.o contentiterator.o reader.o stringdata.o variantdata.o csvimporter.o csvimportconfigure.o signetdev_unix.o passimporter.o passimportunlockdialog.o signetdev_linux.o main.o mainwindow.o loginwindow.o newaccount.o editaccount.o account.o aspectratiopixmaplabel.o loggedinwidget.o changemasterpassword.o searchlistbox.o buttonwaitdialog.o searchfilteredit.o databasefield.o esdb.o systemtray.o passwordedit.o qtlocalpeer.o qtsinglecoreapplication.o qtsingleapplication.o crypto_scrypt_smix_sse2.o crypto_scrypt_smix.o crypto_scrypt.o insecure_memzero.o sha256.o warnp.o signetapplication.o keygeneratorthread.o esdbmodel.o bookmark.o resetdevice.o esdbaccountmodule.o esdbbookmarkmodule.o esdbtypemodule.o esdbactionbar.o accountactionbar.o bookmarkactionbar.o newbookmark.o esdbgenericmodule.o generic.o generictypedesc.o genericactionbar.o newgeneric.o opengeneric.o genericfields.o genericfieldedit.o genericfieldeditfactory.o genericfieldseditor.o linefieldedit.o integerfieldedit.o textblockfieldedit.o typedescedit.o typedesceditor.o signetdevserver.o signetdevserverconnection.o about.o keyboardlayouttester.o settingsdialog.o CompositeKey.o PasswordKey.o FileKey.o AutoTypeAssociations.o Config.o Database.o DatabaseIcons.o Endian.o Entry.o EntryAttachments.o EntryAttributes.o EntrySearcher.o FilePath.o Group.o InactivityTimer.o Metadata.o SignalMultiplexer.o TimeDelta.o TimeInfo.o ToDbExporter.o Tools.o Translator.o Uuid.o Crypto.o CryptoHash.o Random.o SymmetricCipher.o SymmetricCipherGcrypt.o KeePass2Reader.o HashedBlockStream.o LayeredStream.o qtiocompressor.o StoreDataStream.o SymmetricCipherStream.o CsvExporter.o KeePass1Reader.o KeePass2RandomStream.o KeePass2Repair.o KeePass2Writer.o KeePass2XmlReader.o KeePass2XmlWriter.o keepassunlockdialog.o databaseimporter.o databaseimportcontroller.o keepassimporter.o qrc_resources.o moc_passimporter.o moc_passimportunlockdialog.o moc_mainwindow.o moc_loginwindow.o moc_newaccount.o moc_editaccount.o moc_aspectratiopixmaplabel.o moc_loggedinwidget.o moc_changemasterpassword.o moc_searchlistbox.o moc_buttonwaitdialog.o moc_databasefield.o moc_systemtray.o moc_passwordedit.o moc_qtlocalpeer.o moc_qtsinglecoreapplication.o moc_qtsingleapplication.o moc_signetapplication.o moc_keygeneratorthread.o moc_resetdevice.o moc_esdbactionbar.o moc_accountactionbar.o moc_bookmarkactionbar.o moc_newbookmark.o moc_genericactionbar.o moc_newgeneric.o moc_opengeneric.o moc_genericfieldedit.o moc_genericfieldseditor.o moc_signetdevserver.o moc_signetdevserverconnection.o moc_about.o moc_keyboardlayouttester.o moc_settingsdialog.o moc_AutoTypeAssociations.o moc_Config.o moc_Database.o moc_Entry.o moc_EntryAttachments.o moc_EntryAttributes.o moc_Group.o moc_InactivityTimer.o moc_Metadata.o moc_HashedBlockStream.o moc_LayeredStream.o moc_qtiocompressor.o moc_StoreDataStream.o moc_SymmetricCipherStream.o moc_CompositeKey_p.o moc_keepassunlockdialog.o moc_databaseimporter.o moc_databaseimportcontroller.o moc_keepassimporter.o moc_entryrenamedialog.o moc_csvimporter.o moc_csvimportconfigure.o   -L/usr/X11R6/lib64 -l:libgcrypt.a -l:libgpg-error.a -l:libz.a -lQt5Widgets -lQt5X11Extras -lQt5Gui -lQt5WebSockets -lQt5Network -lQt5Concurrent -lQt5Core -lGL -lpthread 
/usr/bin/ld: keyboardlayouttester.o: undefined reference to symbol 'XGetKeyboardMapping'
/usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:719: recipe for target 'signet' failed
make: *** [signet] Error 1

**Comment by nthdimtech** [comment]
Looks like a recent change I made to make a mostly static build got 
accidentally committed. My change omitted the "-lX11" line so I'm not 
sure how it worked for me. Anyways if you pull the latest it should work 
now

**Comment by ngiger** [comment]
Thanks. This fixed it!
