### ISSUE TITLE
v.0.9.9 crashes at launch on macOS (10.12.6)

### ISSUE THREAD

**Issue by Airgunster** [nthdimtech/signet-client#49]
Hi Neils,

I've just tested new v.0.9.9, and it unfortunately crashes every time I'm trying to launch it.

```
Process:               signet [22539]
Path:                  /Applications/signet-0.9.9.app/Contents/MacOS/signet
Identifier:            com.yourcompany.signet
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           signet [22539]
User ID:               919199116

Date/Time:             2018-02-17 22:47:13.169 +0000
OS Version:            Mac OS X 10.12.6 (16G1212)
Report Version:        12
Anonymous UUID:        BB94E835-0504-CCE0-5C1A-7273B470A71E


Time Awake Since Boot: 42000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x00000000000000d8
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [0]
```

Downloaded from: https://nthdimtech.com/downloads/signet-releases/0.9.9/macos/signet-0.9.9.dmg

---

I've also tested previous version v.0.9.8.1-rc3 (https://nthdimtech.com/downloads/signet-releases/0.9.8/macos/signet-0.9.8.1-rc3.dmg) and it works fine.

Could you please have a look?

Thanks a lot in advance,
Alexey

**Comment by nthdimtech** [comment]
I think I've fixed it. Version 0.9.9 is first release where I've used Qt5 from Brew and I've discovered there is a bug in the version of "macdeployqt" in Qt 5.8 distributed from Brew that causes the Qt dependencies to not get bundled. I've upgraded to Qt 5.10 in Brew and uploaded a new DMG. I don't understand why this presented as a SYSSEGV instead of a link error but I'm still thinking this is the most likely cause. Could you give the new archive a try and let me know how it works?

**Comment by batmac** [comment]
just to say I had this exact problem you've described:

[bat:/Applications]  $ open signet-0.9.9.app
LSOpenURLsWithRole() failed with error -10810 for the file /Applications/signet-0.9.9.app.
[bat:/Applications]  $ signet-0.9.9.app/Contents/MacOS/signet
dyld: Library not loaded: /usr/local/Cellar/qt/5.8.0_2/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /Applications/signet-0.9.9.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Reason: image not found
Abort trap: 6

I've downloaded it again 5min ago and It is ok now (with the latest dmg)
Thanks a lot!

> Le 18 févr. 2018 à 02:47, Neils Nesse <notifications@github.com> a écrit :
> 
> I think I've fixed it. Version 0.9.9 is first release where I've used Qt5 from Brew and I've discovered there is a bug in the version of "macdeployqt" in Qt 5.8 distributed from Brew that causes the Qt dependencies to not get bundled. I've upgraded to Qt 5.10 in Brew and uploaded a new DMG. I don't understand why this presented as a SYSSEGV instead of a link error but I'm still thinking this is the most likely cause. Could you give the new archive a try and let me know how it works?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Baptiste Canton

**Comment by nthdimtech** [comment]
@batmac Okay so the problem does present as a link error, at least for you. I'm curious why it fails with a SIGSEGV for @Airgunster 

@Airgunster Could you share the full crash log you saw with the original 0.9.9 release. I'd like to understand MacOS failure modes better even if the new build fixes the problem for you as well

**Comment by Airgunster** [comment]
> @Airgunster Could you share the full crash log you saw with the original 0.9.9 release. I'd like to understand MacOS failure modes better even if the new build fixes the problem for you as well

Sure, here it is,
[2018-02-17T22-47+0000_signet-0.9.9-original-crash.txt](https://github.com/nthdimtech/signet-desktop-client/files/1734813/2018-02-17T22-47.0000_signet-0.9.9-original-crash.txt)

---

Also tested [the latest one](https://nthdimtech.com/downloads/signet-releases/0.9.9/macos/signet-0.9.9.dmg) and can also confirm that it now works fine.

Thanks a lot Neils.

**Comment by nthdimtech** [comment]
Good to hear. Thanks for the info
