### ISSUE TITLE
esdbmodel: Invalid index warnings for endRemoveRows()

### ISSUE THREAD

**Issue by tuxlifan** [nthdimtech/signet-client#61]
During search, both when adding and deleting characters, sometimes the following message is displayed on the console:

> QAbstractItemModel::endRemoveRows: Invalid index (...) in model QAbstractItemModel(...)

where "index ( N, M )" has varying values for N (between 1 and 9 so far) and M=0.

It seems to not impede the functionality as far as I could discern.

**Comment by nthdimtech** [comment]
I've reviewed the code and can't seem to find any likely cause. Next time you notice it see if you can narrow it down a bit.

**Comment by tuxlifan** [comment]
Apparently it only happens in the **else branch** of `if (!item->isLeafItem()) `.

Sometimes the first time I try to trigger it with a search it doesn't happen but only on the second and subsequent tries.
I'm trying to narrow down my database to arrive at a small sample that I might be able to anonymize but it is quite a slow process going one-by-one and re-checking if I can still trigger the error before deleting the next entry...
Any ideas how I could poke the model more directly? gdb doesn't seem to be of great help - or at least I haven't found a way to make it display more of what's going on...

**Comment by tuxlifan** [comment]
I've now found a minimal example:

On a wiped device create the following 5 accounts (`Account name`,`Group/Subgroup`):
1. `i`,`A/Asub`
2. `i`,`B`
3. `a`,`B`
4. `b`,`B`
5. `c`,`B/Bsub`

For the bug to trigger the accounts `a`, `b` and `c` MUST NOT contain the character `i` in their Account name (but MAY contain it in their Group or Subgroup name, in which case the second account must be in the same Group as a and b for which c is in a subgroup).

Proceed as follows:

- Start the signet-desktop-client from a terminal or otherwise capture its output
- unlock the device
- Type `i` into the search box.
Everything should be ok and the account list filtered, without error message.
- Delete the contents of the search box (either with a mouse click on the x button or by backspacing)
- Type `i` into the search box.
You should see an error message `QAbstractItemModel::endRemoveRows:  Invalid index ( 2 , 0 ) in model QAbstractItemModel(0xnnnnnnn)`
- A search for any character except `a`, `b` and `c` will trigger the same error message (from the second search attempt forward)

**Comment by nthdimtech** [comment]
I tried to reproduce this with the 0.9.12 build and could not. The listbox code has changed since this issue was filed and the Qt version was upgraded 5.8 to 5.12.
