### ISSUE TITLE
KeyboardLayoutTester has no signal close()

### ISSUE THREAD

**Issue by tuxlifan** [nthdimtech/signet-client#63]
Client version 0.9.9 and later.

When the keyboard configurator window appears, the console shows

> QObject::connect: No such signal KeyboardLayoutTester::close()

messages.

Sometimes also 

> QXcbConnection: XCB error: 3 (BadWindow), sequence: 2089, resource id: 4203652, major code: 40 (TranslateCoords), minor code: 0

or similar shows up, which I presume is the result of the missing close() not being connected to deleteLater()?
See
https://github.com/nthdimtech/signet-desktop-client/blob/master/client/keyboardlayouttester.cpp#L229

**Comment by nthdimtech** [comment]
Just fixed the close() signal issue. I'll need a bit more information to tackle the XcbConnection error since I've never seen it.

**Comment by nthdimtech** [comment]
I have done more testing and haven't seen the XcbConnection error above. I'm going to close this for now.
