### ISSUE TITLE
Compile for ARM GNU-Linux

### ISSUE THREAD

**Issue by garro95** [nthdimtech/signet-client#69]
I want to compile the client on a GNU/Linux ARM computer.
If I follow the instructions, I get an error about -msse4.1 being an unrecognized option to gcc.
If I remove the option from the Makefile I get another error about a library non existing. How can I compile it?

**Comment by nthdimtech** [comment]
Sorry for the late response. The client should be pretty close to being ready for GNU/Linux ARM computer since I got the client running on Android recently. Removing the "-msse4.1" is the right move since this is an Intel specific feature. What was the library the Makefile wasn't finding?

**Comment by garro95** [comment]
The error message I get is:
```
scrypt/crypto_scrypt_smix_sse2.c:32:33: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
                       ^
compilation terminated.
Makefile:1675: recipe for target 'crypto_scrypt_smix_sse2.o' failed
make: *** [crypto_scrypt_smix_sse2.o] Error 1
```

**Comment by dragon788** [comment]
SSE2 also probably isn't available for ARM as that is another Intel extension.

**Comment by nthdimtech** [comment]
It is not. I just pushed a change I hope will fix it. All I did was expand the fixes I made for Android to non x86_64 desktop targets. Let me know if it works for you

**Comment by garro95** [comment]
This worked on my machine. Thank you
