### ISSUE TITLE
Open file write dialog when performing scheduled database backup

### ISSUE THREAD

**Issue by nthdimtech** [nthdimtech/signet-client#7]
This should make it more clear to users where the backup is going so they know where to look for it if they need to recover the data

**Comment by dragon788** [comment]
I think this is already implemented?

I do like how when prompted to run a scheduled backup it pops up a file dialog with the current date, it is very frustrating in OTHER software having to add the date-stamp yourself, it's a poor backup software that clobbers your "only" backup with a new one of the same name, just asking for corruption or other issues.

**Comment by nthdimtech** [comment]
You're right, I just didn't get around to closing the bug. I'm glad you like the naming behavior. The backups are so small relative to today's hard disk sizes that I see no harm in letting the dated backup files accumulate. If disk space is running low the user can pick how many they want to delete and still feel sure they aren't losing anything.
