### ISSUE TITLE
Signet CSV Import crashes on Windows 10 

### ISSUE THREAD

**Issue by paulichristian** [nthdimtech/signet-client#73]
I've two signets, exported my data to a CSV-File, started the client with the second signet (the one where I want to update the accounts/passwords, etc..) and selected the file in the import-menu. The client simply crashes - see attached app crash folder from Windows 10.
Thank you for any feedback.
Christian
[AppCrash_signet-0.9.10-64_1cb72adb1fa09fe3dedea24aaadac788ae2018_c17c9229_2dd1e96f.zip](https://github.com/nthdimtech/signet-desktop-client/files/1998291/AppCrash_signet-0.9.10-64_1cb72adb1fa09fe3dedea24aaadac788ae2018_c17c9229_2dd1e96f.zip)

**Comment by nthdimtech** [comment]
If you want an exact clone of your data the best way is take a backup from one device and restore it to another. You will only get the "restore" option if the destination device is logged out.

In any case the CSV import shouldn't be crashing and I'll look into that

**Comment by nthdimtech** [comment]
Okay I looked into this and I am able reproduce the crash on 0.9.10 on Linux but it does not reproduce on the top of tree. I believe I fixed this issue with commit 75ddb5. I'm going to close this for now and we can reopen it if anyone sees it after I release 0.9.11 (should be later this week)
