### ISSUE TITLE
Add support for user defined data types

### ISSUE THREAD

**Issue by Madbeefer** [nthdimtech/signet-client#79]
If I could add more than just Accounts, Bookmarks and Misc that would be helpful.

**Comment by nthdimtech** [comment]
I will be doing a release this week. Once it is done addressing this need will be my next priority.

The plan is to have each user type added under the pulldown to have their own set of predefined fields just like accounts always have "username", "password", "url", etc. I haven't worked out how exactly this will be specified but I'll describe it here when I do.

**Comment by nthdimtech** [comment]
Added in 0.9.12!
