### ISSUE TITLE
Emulation mode to read database contents without a device connected

### ISSUE THREAD

**Issue by nthdimtech** [nthdimtech/signet-client#8]

**Comment by dragon788** [comment]
This would be fantastic, especially if you could also edit the database offline, though I hope that it is protected by GPG encryption or the same passphrase as the Signet device itself.

**Comment by nthdimtech** [comment]
I think I'll go with editing with a warning about concurrency problems if the database is also in use in a device. Perhaps a read only flag that would need to be switched off.

My plan was to just use the same encryption and authentication that the device uses. As it is the backups are simply dumps of the database region of the microcontrollers flash. If that crypto isn't strong enough I'd rather improve it directly than wrap it with gpg or anything else.

On January 3, 2018 4:35:35 PM PST, dragon788 <notifications@github.com> wrote:
>This would be fantastic, especially if you could also edit the database
>offline, though I hope that it is protected by GPG encryption or the
>same passphrase as the Signet device itself.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nthdimtech/signet-desktop-client/issues/8#issuecomment-355167661

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Asara** [comment]
Just curious as to what the status of this is.  Pretty much the only feature preventing me from using my device full time.

**Comment by nthdimtech** [comment]
I'm currently working on the mobile client which is also something that 
people are eagerly waiting for. I do understand how essential this 
feature is however and I will be working on it when I get to good 
stopping point on the mobile side.

**Comment by nthdimtech** [comment]
This feature is now in the top of tree. It should make it out in a release this coming week.

**Comment by nthdimtech** [comment]
Release 0.9.11 is out and includes this feature
