### ISSUE TITLE
Creating new drop down menu category?

### ISSUE THREAD

**Issue by Asara** [nthdimtech/signet-client#86]
Hey friends,

I am wondering is it currently possible to create a new drop-down menu grouping?

The defaults are Accounts/Bookmarks/Misc, but I would like to create some more custom ones.  Is that possible?

Thanks!

**Comment by nthdimtech** [comment]
This feature hasn't been added yet but I have been working on it recently. See issue #79. I'm planning to add this to the next release which should come out in about 2 weeks.
