### ISSUE TITLE
Validation needed on input text lengths

### ISSUE THREAD

**Issue by nthdimtech** [nthdimtech/signet-client#89]

**Comment by timetoseek** [comment]
Testing Update: I installed the new firmware build (1.3.3) and compiled the client with the latest updates.  I tried to paste about 5.7k of text data into the "Text Block" field.  When I click Save, the "Press Button" screen appears for a split second, the Signet button does not flash blue, and nothing is saved. So, it appears that the latest updates have solved the issues previously identified.  What is still needed, as you have noted, is a validation of input text lengths. Maybe a visible character counter, plus an error message to the user if they exceed the limit. Below is a screen print for your reference. Thank you!
![text_block_validation_new_client_new_firmware](https://user-images.githubusercontent.com/26972658/43852302-bba9baa0-9af1-11e8-8981-666355273d45.jpg)

**Comment by nthdimtech** [comment]
Fixed by af5700c. The save button is automatically disabled when an entry exceeds the 2k data limit and a visible warning appears. Once the data size is small enough again the save button is enabled again.

**Comment by timetoseek** [comment]
Just tested, works great!!!  Thank you!!!

![fix_pic1](https://user-images.githubusercontent.com/26972658/44686398-f0b74800-aa02-11e8-9525-06b0fcf7085c.jpg) ![fix_pic2](https://user-images.githubusercontent.com/26972658/44686399-f0b74800-aa02-11e8-9674-fba5b302fa43.jpg)
