### ISSUE TITLE
can't build mac app

### ISSUE THREAD

**Issue by scottjl** [nthdimtech/signet-client#94]
issue resolved..

**Comment by nthdimtech** [comment]
Glad to hear it. To get it to build did you need to do anything not covered in the online instructions?

 http://nthdimtech.com/signet/how-to-build-the-client-from-source/ 

I just want to make sure the instructions don't have a problem before closing this.

**Comment by scottjl** [comment]
Actually I was wrong. I can't get it to build. Had a ton of errors. Will
post them tomorrow. :(

**Comment by espoelstra** [comment]
@scottjl I just build on macOS 10.13.6 with some warnings, but no fatal errors. What messages were you seeing?

**Comment by nthdimtech** [comment]
I've done several MacOS builds recently and the MacOS CI tests are passing. I'm going to close this due to lack of information.
