### ISSUE TITLE
Missing data types

### ISSUE THREAD

**Issue by izghitu** [nthdimtech/signet-client#96]
Hi,

Not sure if this is client related or not or if I am not doing something properly but in the images from https://www.nthdimtech.com/signet/getting-started/ I can see there are 6 data types. Not sure why but mine shows only 3 of those which are Accounts, Bookmarks and Misc.

Any way to make the others show?

Thanks

**Comment by nthdimtech** [comment]
This is part of issue #79 which will be part of the next release. You should follow that issue to see when progress is made.
