### ISSUE TITLE
Restore from file issue

### ISSUE THREAD

**Issue by izghitu** [nthdimtech/signet-client#97]
Hi,

On the windows desktop client when I reinitialize the device and then do a restore from file then the restore progress bar starts. When that happens then I can see the "Device backup" window prompt, when I click no the progress bar goes +1% then again that window prompts and it keeps going this way in a loop until it gets to 100%. So I have to click no 100 times until the device restore from file completes.

Please check.
Thanks

**Comment by nthdimtech** [comment]
I just tried to replicate this on Windows 10 using client version 0.9.11 and I am not seeing any extra dialogs. What windows and client version were you using?

**Comment by izghitu** [comment]
please check this video showing the issue:
https://screencast-o-matic.com/watch/cFQ6iZqE3b

**Comment by nthdimtech** [comment]
Thanks for that. I see, somehow the "backup is too old" check is being executed at this time. I had *made* a backup in order to attempt to replicate the issue which prevented the problem. I expect this will be easy to fix.

**Comment by nthdimtech** [comment]
Fixed in 0.9.12. The backup check only occurs after unlock now.
