### ISSUE TITLE
Strip release binary

### ISSUE THREAD

**Issue by Necklaces** [nthdimtech/signet-client#98]
I noticed the GNU/Linux binaries (https://nthdimtech.com/downloads/signet-releases/0.9.11/gnu-linux/) are 22 megabytes (actually 23 mebibytes), but your server (nthdimtech.com) either has rate limiting or is slow (at least for me it takes 3 minutes to download). I suggest stripping the binary during release:

```
strip signet-0.9.11
```

This saves almost 4 mebibytes (from 23132204 to 19491360).

Of course, if you want to save more space you could always compress the binary, I tried using bz2 and it got down to 8Mb (8403274).

**Comment by nthdimtech** [comment]
Good catch. I wiill make it a point to strip the next binary release.
I'll also probably release a compressed version of the binary as well to
shoot for an even lower size. I wonder if it would be better to only
release a compressed version. That way the execute mode can be encoded
in the archive. Either way at least one extra step needs to be taken
(decompress vs chmod) so there might not be any downsides.

**Comment by nthdimtech** [comment]
I ended up forgetting this for the initial 0.9.12 release but I've just fixed it and added it to my release checklist. Deployment issues in future should be handled in this repo I think: https://github.com/nthdimtech/nthdimtech-site
